[project]
name = "attention-math"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.5.0",
    "numpy>=1.21.0",
    "seaborn>=0.11.0",
    "torch>=1.9.0",
]
